# Default notebook

This default notebook is executed using a Lakeflow job as defined in resources/sample_job.job.yml.

In [16]:
from databricks.connect import DatabricksSession

spark = DatabricksSession.builder.serverless().profile("dev").getOrCreate()

In [17]:
spark.sql("CREATE CATALOG IF NOT EXISTS sales_data")

DataFrame[]

In [18]:
spark.sql("SHOW SCHEMAS").show()

+------------------+
|      databaseName|
+------------------+
|           default|
|information_schema|
+------------------+

In [43]:
spark.sql("USE CATALOG sales_data")
spark.sql("USE SCHEMA sales_tables")

DataFrame[]

In [44]:
print(spark.catalog.currentCatalog())
print(spark.catalog.currentDatabase())

sales_data
sales_tables

In [46]:
spark.sql("SHOW TABLES IN sales_data.sales_tables").show()

+------------+----------------+-----------+
|    database|       tableName|isTemporary|
+------------+----------------+-----------+
|sales_tables|bronze_customers|      false|
|sales_tables|   bronze_orders|      false|
|sales_tables| bronze_products|      false|
|sales_tables|  bronze_regions|      false|
|sales_tables|      fact_sales|      false|
|sales_tables|  gold_customers|      false|
|sales_tables|   gold_products|      false|
|sales_tables|silver_customers|      false|
|sales_tables|   silver_orders|      false|
|sales_tables| silver_products|      false|
|sales_tables|  silver_regions|      false|
+------------+----------------+-----------+

In [47]:
df = spark.read.table("sales_data.sales_tables.fact_sales")
df.show(5)

+--------+-------------------+------------+--------+---------------+-----------------+--------------+------+--------+
|order_id|         order_date|total_amount|quantity|  customer_name|    customer_city|  product_name| brand|category|
+--------+-------------------+------------+--------+---------------+-----------------+--------------+------+--------+
|  O00001|2023-03-22 00:00:00|     2022.87|       3|     Dean Young|South Natashastad|Politics Along|LENOVO|    Home|
|  O00002|2023-06-30 00:00:00|     3560.74|       2|  Samuel Martin|       Mariahside|Success Always|  DELL|    Home|
|  O00003|2023-11-06 00:00:00|     5903.52|       3|    John Meyers|     North Teresa| Despite Dream|  SONY|  Sports|
|  O00004|2024-02-27 00:00:00|     4107.99|       3|Theresa Ramirez|    Mcfarlandbury|     Thus Make|LENOVO|    Toys|
|  O00005|2024-10-13 00:00:00|     5784.95|       5|  Lori Reynolds|     Browningland|     Edge Keep|REVLON|    Toys|
+--------+-------------------+------------+--------+---------------+-----------------+--------------+------+--------+
only showing top 5 rows

In [38]:
print(spark.catalog.currentCatalog())

sales_data

In [30]:
spark.sql("CREATE CATALOG IF NOT EXISTS sales_data")
spark.sql("CREATE SCHEMA IF NOT EXISTS sales_data.sales_table")

DataFrame[]

In [32]:
spark.sql("SHOW TABLES").show()

+--------+---------+-----------+
|database|tableName|isTemporary|
+--------+---------+-----------+
+--------+---------+-----------+

In [48]:
spark.sql("drop schema if exists sales_data.sales_table cascade")

DataFrame[]